export const MockDataCard = [
    {
        id: 0,
        image: "https://daisyui.com/images/stock/photo-1606107557195-0e29a4b5b4aa.jpg",
        icon: "./github.png",
        title: "Green Sculpt",
        description: "Web application for exercise.",
        date: "November, 2023 - February, 2024",
        location: "| Generation Thailand",
        titlecolor: "text-[#8BCA00]"
    },
    {
        id: 1,
        image: "./lineman.png",
        icon: "./link.png",
        title: "LINE MAN Coupon Book",
        description: "A feature ‘Coupon Book’ where users can simply find and use their coupons.",
        date: "May, 2023",
        location: "| LINE MAN",
    },
    {
        id: 2,
        image: "./mute-maid-service.png",
        icon: "./link.png",
        title: "Mute Maid Service",
        description: "A mobile application for maid service by housekeeper with hearing impaired.",
        date: "August, 2022 - May, 2023",
        location: "| KMUTT",
    },
    {
        id: 3,
        image: "./cfood.png",
        icon: "./link.png",
        title: "CFood",
        description: "Design an application for healthy food lovers.",
        date: "March, 2022 - May, 2022",
        location: "| KMUTT",
    },
    {
        id: 4,
        image: "./chitchat.png",
        icon: "./link.png",
        title: "CHIT CHAT",
        description: "Web application for chatting online.",
        date: "September, 2021 - December, 2021",
        location: "| KMUTT",
    },
    {
        id: 5,
        image: "./delluna.png",
        icon: "./link.png",
        title: "Hotel Del Luna",
        description: "Web application for hotel management.",
        date: "February, 2021 - June, 2021 ",
        location: "| KMUTT",
    },

];
